### ISSUE TITLE
Throws if .max and .min are set to the same value

### ISSUE THREAD

**Issue by jasonkester** [dalisc/color-scales-js#5]
In the common scenario where you're setting the max and min values of your colorscale object from a list of values, and that list size happens to be one, you'll end up with the max and min of your range set to the same number.

In that case, this library will throw when you ask for the color for your single value.

A testcase that demonstrates this:
```
const cs = new ColorScale(35, 35, ['#555555', '#ffffff'], 1);
console.log(cs.getColor(35))

TypeError: Cannot read property 'r' of undefined
    at ColorScale.getColor ([...]node_modules\color-scales\lib\ColorScale.js:35:48)
```

A workaround is to check your max and min after setting them to ensure they don't end up with the same value.  As in:

```
if (cs.max === cs.min) {
  cs.max++;
}
```

**Comment by dalisc** [comment]
Good catch! However, it is expected that the list size should be at least 2. There isn't a reason to use this plugin for a list size of 1. Perhaps I would assert that list size has to be at least 2 instead.

**Comment by dalisc** [comment]
Very curious as to how this happened as I have set an assertion that min must be strictly less than max in `validators.ts`:
```ts
export function validateMinMaxValues(min: number, max: number) {
  if (min === max) {
    throw new Error('The minimum value cannot be equal to the maximum value.');
  } else if (min > max) {
    throw new Error('The minimum value must be less than the maximum value.');
  }
}
```

I have also accounted for this edge case in my tests in `ColorScale.test.ts`:

```ts
test('Error thrown when min value equals max value', () => {
  expect(() => new ColorScale(0, 0, ['#000000', '#ffffff'])).toThrow(
    'The minimum value cannot be equal to the maximum value.',
  );
});
```

Anyway I've tried to reproduce with the same code you have but it throws the expected message above which is the expected behaviour. This error could be due something else, perhaps your code or package manager. Please also try updating your color-scales to the latest version. Also, there is really no use case of instantiating a ColorScale with min == max. Will close this issue!

**Comment by jasonkester** [comment]
I got there by manually setting .min and .max after creating the object.

My use case is for coloring regions on a map.  I keep a persistent ColorScale object around and set its .min and .max to suit the data I happen to have for the map at any time.  At any moment, there can be 0-n values that need to be represented as shaded regions on the map, so having exactly one is certainly a possibility.  

Just refusing to work for that case isn't really a fix.

.min-- solves it nicely, since then the value gets the .max color.

**Comment by jasonkester** [comment]
I bet your validators only fire on object creation, rather than whenever a property changes or when .getColor is called.

Here's a better testcase:

```
const cs = new ColorScale(0,1, ['#555555', '#ffffff'], 1);
cs.min = 35;
cs.max = 35;
console.log(cs.getColor(35))

TypeError: Cannot read property 'r' of undefined
    at ColorScale.getColor ([...]node_modules\color-scales\lib\ColorScale.js:35:48)
```

**Comment by dalisc** [comment]
That's an interesting use case. Thanks for explaining it! I'll allow this:
```
if (cs.max === cs.min) {
  cs.max++;
}
```

You are right that the validators only fire on object creation. I will create a patch and notify you.

**Comment by dalisc** [comment]
It makes better sense that you should cs.max++ on your side instead if you detect that the new min and max values you are about to set are equal. WDYT?

> .min-- solves it nicely, since then the value gets the .max color.

This reason that you gave is also very specific to your situation

I cannot find a good reason to allow cs.min == cs.max for the ColorScale object from a design perspective. We would have an issue of whether it gets the max or min color, and even worse in the case where people have more than 2 color stops. I'm open to hearing better arguments.

**Comment by dalisc** [comment]
Closing as there are no response and it does not make sense to make this arbitrary fix.
